/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author DELL
 */
public class BusquedaID extends javax.swing.JFrame {
     //private List<Empleados> listaEmpleados;
    /**
     * Creates new form BusquedaID
     */
    public BusquedaID() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelID = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoID = new javax.swing.JTextPane();
        IngresarID = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        BotonBuscarID = new javax.swing.JButton();
        BotonMenu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelID.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));

        InfoID.setBackground(new java.awt.Color(102, 102, 102));
        InfoID.setCaretColor(new java.awt.Color(102, 102, 102));
        InfoID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(InfoID);

        IngresarID.setBackground(new java.awt.Color(51, 51, 51));
        IngresarID.setForeground(new java.awt.Color(153, 153, 153));
        IngresarID.setText("Ingresar ID");
        IngresarID.setBorder(null);
        IngresarID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarIDMousePressed(evt);
            }
        });
        IngresarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarIDActionPerformed(evt);
            }
        });

        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Ingrese el ID de Empleado:");

        BotonBuscarID.setBackground(new java.awt.Color(0, 153, 255));
        BotonBuscarID.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscarID.setText("Buscar");
        BotonBuscarID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarIDMouseClicked(evt);
            }
        });
        BotonBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarIDActionPerformed(evt);
            }
        });

        BotonMenu.setBackground(new java.awt.Color(0, 102, 102));
        BotonMenu.setForeground(new java.awt.Color(255, 255, 255));
        BotonMenu.setText("Menu");
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });

        Encabezado.setBackground(new java.awt.Color(0, 102, 255));
        Encabezado.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar ID");
        Encabezado.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("DNOM-UTH - 2023");

        javax.swing.GroupLayout PanelIDLayout = new javax.swing.GroupLayout(PanelID);
        PanelID.setLayout(PanelIDLayout);
        PanelIDLayout.setHorizontalGroup(
            PanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIDLayout.createSequentialGroup()
                .addGroup(PanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIDLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIDLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(IngresarID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIDLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIDLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(BotonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(BotonBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIDLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelIDLayout.createSequentialGroup()
                        .addGap(770, 770, 770)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelIDLayout.setVerticalGroup(
            PanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIDLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(IngresarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(PanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2))
        );

        getContentPane().add(PanelID, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

    // Constructor que recibe la lista de empleados
    
    private void restablecer() {
        String IDPlaceholder = "Ingresar ID";

        if (IngresarID.getText().isEmpty()) {
            IngresarID.setText(IDPlaceholder);
            IngresarID.setForeground(new Color(153, 153, 153));
        }
    }
    private void IngresarIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarIDMousePressed
        // TODO add your handling code here:
        if (IngresarID.getText().equals("Ingresar ID")){
            IngresarID.setText("");
            IngresarID.setForeground(Color.white);
        }else{
            restablecer();
        }
    }//GEN-LAST:event_IngresarIDMousePressed

    private void IngresarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarIDActionPerformed
    private Empleados buscarEmpleadoPorID(String idBuscado) {
        List<Empleados> listadatos = Datos.obtenerListaEmpleados();

        for (Empleados empleado : listadatos) {
            if (empleado.getID().equals(idBuscado)) {
                return empleado; // Se encontró el empleado con el ID buscado
            }
        }
        return null; // No se encontró ningún empleado con el ID buscado
    }
    private void BotonBuscarIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarIDMouseClicked
        // TODO add your handling code here:
        String idBuscado = IngresarID.getText();

        // Realiza la búsqueda en la lista de empleados (o en tu fuente de datos)
        Empleados empleadoEncontrado = buscarEmpleadoPorID(idBuscado);

        // Si se encontró el empleado, muestra la información en el JTextPane
        if (empleadoEncontrado != null) {
            String infoEmpleado = "ID: " + empleadoEncontrado.getID() + "\n";
            infoEmpleado += "Nombre: " + empleadoEncontrado.getNombre() + "\n";
            infoEmpleado += "Edad: " + empleadoEncontrado.getEdad() + "\n";
            infoEmpleado += "DNI: " + empleadoEncontrado.getDni() + "\n";
            infoEmpleado += "Tipo: " + empleadoEncontrado.getTipo() + "\n";
            infoEmpleado += "Fecha: " + empleadoEncontrado.getFecha() + "\n";
            infoEmpleado += "Salario: " + empleadoEncontrado.getSalario() + "\n";
            infoEmpleado += "Cargo: " + empleadoEncontrado.getCargo() + "\n";

            InfoID.setText(infoEmpleado);
        } else {
            // Si no se encontró el empleado, muestra un mensaje en el JTextPane
            InfoID.setText("Empleado no encontrado.");
        }
    }//GEN-LAST:event_BotonBuscarIDMouseClicked

    private void BotonBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarIDActionPerformed

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        // TODO add your handling code here:
        Menu menuOpciones = new Menu();
        menuOpciones.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BotonMenuMouseClicked

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BotonMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //List<Empleados> listaDatos = new ArrayList<>();

        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new BusquedaID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarID;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JTextPane InfoID;
    private javax.swing.JTextField IngresarID;
    private javax.swing.JPanel PanelID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
