/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Dialog;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Registrar extends javax.swing.JFrame {
    private int contadorRegistros = 0;
    private String cargoSeleccionado = "Seleccionar cargo";
    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        OpcionesCargos = new javax.swing.JComboBox<>();
        OpcionesCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnico", "Ingeniero", "Vendedor", "Servicio al Cliente"}));
        OpcionesCargos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpcionesCargosItemStateChanged(evt);
            }
        });
       this.setLocationRelativeTo(null);
       setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarPanel = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegistrarNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        RegistrarEdad = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        RegistrarDNI = new javax.swing.JTextField();
        RegistrarTipo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        RegistrarFecha = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        RegistrarSalario = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        BotonRegistrar = new javax.swing.JButton();
        OpcionesCargos = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        BotonMenu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1010, 640));

        RegistrarPanel.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarPanel.setPreferredSize(new java.awt.Dimension(2000, 640));

        Encabezado.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Empleados");

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1702, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE: ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CARGO:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EDAD:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TIPO:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FECHA DE NACIMIENTO:");

        RegistrarNombre.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarNombre.setForeground(new java.awt.Color(153, 153, 153));
        RegistrarNombre.setText("Ingresar Nombre");
        RegistrarNombre.setBorder(null);
        RegistrarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarNombreMousePressed(evt);
            }
        });
        RegistrarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNombreActionPerformed(evt);
            }
        });

        RegistrarEdad.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarEdad.setForeground(new java.awt.Color(153, 153, 153));
        RegistrarEdad.setText("Ingresar Edad");
        RegistrarEdad.setBorder(null);
        RegistrarEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarEdadMousePressed(evt);
            }
        });
        RegistrarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEdadActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2 logo.png"))); // NOI18N

        RegistrarDNI.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarDNI.setForeground(new java.awt.Color(153, 153, 153));
        RegistrarDNI.setText("Ingresar DNI");
        RegistrarDNI.setBorder(null);
        RegistrarDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarDNIMousePressed(evt);
            }
        });
        RegistrarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDNIActionPerformed(evt);
            }
        });

        RegistrarTipo.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarTipo.setForeground(new java.awt.Color(153, 153, 153));
        RegistrarTipo.setText("Ingresar Tipo");
        RegistrarTipo.setBorder(null);
        RegistrarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarTipoMousePressed(evt);
            }
        });
        RegistrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarTipoActionPerformed(evt);
            }
        });

        RegistrarFecha.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarFecha.setForeground(new java.awt.Color(153, 153, 153));
        RegistrarFecha.setText("Ingresar Fecha de Nacimiento");
        RegistrarFecha.setBorder(null);
        RegistrarFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarFechaMousePressed(evt);
            }
        });
        RegistrarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarFechaActionPerformed(evt);
            }
        });

        RegistrarSalario.setBackground(new java.awt.Color(51, 51, 51));
        RegistrarSalario.setForeground(new java.awt.Color(153, 153, 153));
        RegistrarSalario.setText("Ingresar Salario");
        RegistrarSalario.setBorder(null);
        RegistrarSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarSalarioMousePressed(evt);
            }
        });
        RegistrarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarSalarioActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar2.png"))); // NOI18N

        BotonRegistrar.setBackground(new java.awt.Color(0, 153, 255));
        BotonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseClicked(evt);
            }
        });
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        OpcionesCargos.setBackground(new java.awt.Color(51, 51, 51));
        OpcionesCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Cargo", "Tecnico", "Ingenierio", "Vendedor", "Servicio al Cliente" }));
        OpcionesCargos.setBorder(null);
        OpcionesCargos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpcionesCargosItemStateChanged(evt);
            }
        });
        OpcionesCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpcionesCargosMouseClicked(evt);
            }
        });
        OpcionesCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesCargosActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SALARIO:");

        BotonMenu.setBackground(new java.awt.Color(0, 102, 102));
        BotonMenu.setForeground(new java.awt.Color(255, 255, 255));
        BotonMenu.setText("Menu");
        BotonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMenuMouseClicked(evt);
            }
        });
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("DNOM - UTH - 2023");

        javax.swing.GroupLayout RegistrarPanelLayout = new javax.swing.GroupLayout(RegistrarPanel);
        RegistrarPanel.setLayout(RegistrarPanelLayout);
        RegistrarPanelLayout.setHorizontalGroup(
            RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegistrarPanelLayout.createSequentialGroup()
                .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RegistrarPanelLayout.createSequentialGroup()
                                .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(138, 138, 138)
                                .addComponent(jLabel9))
                            .addGroup(RegistrarPanelLayout.createSequentialGroup()
                                .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OpcionesCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegistrarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(BotonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                        .addGap(741, 741, 741)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrarPanelLayout.setVerticalGroup(
            RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarPanelLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                        .addComponent(RegistrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(RegistrarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(RegistrarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(RegistrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(RegistrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(RegistrarSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OpcionesCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegistrarPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        getContentPane().add(RegistrarPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Método para restablecer los campos de entrada
    private void restablecer() {
        String nombrePlaceholder = "Ingresar Nombre";
        String edadPlaceholder = "Ingresar Edad";
        String dniPlaceholder = "Ingresar DNI";
        String tipoPlaceholder = "Ingresar Tipo";
        String fechaPlaceholder = "Ingresar Fecha de Nacimiento";
        String salarioPlaceholder = "Ingresar Salario";

        if (RegistrarNombre.getText().isEmpty()) {
            RegistrarNombre.setText(nombrePlaceholder);
            RegistrarNombre.setForeground(new Color(153, 153, 153));
        }

        if (RegistrarEdad.getText().isEmpty()) {
            RegistrarEdad.setText(edadPlaceholder);
            RegistrarEdad.setForeground(new Color(153, 153, 153));
        }

        if (RegistrarDNI.getText().isEmpty()) {
            RegistrarDNI.setText(dniPlaceholder);
            RegistrarDNI.setForeground(new Color(153, 153, 153));
        }

        if (RegistrarTipo.getText().isEmpty()) {
            RegistrarTipo.setText(tipoPlaceholder);
            RegistrarTipo.setForeground(new Color(153, 153, 153));
        }

        if (RegistrarFecha.getText().isEmpty()) {
            RegistrarFecha.setText(fechaPlaceholder);
            RegistrarFecha.setForeground(new Color(153, 153, 153));
        }

        if (RegistrarSalario.getText().isEmpty()) {
            RegistrarSalario.setText(salarioPlaceholder);
            RegistrarSalario.setForeground(new Color(153, 153, 153));
        }
    }
    // Método para limpiar los campos de entrada
    private void limpiarCampos() {
        RegistrarNombre.setText("");
        RegistrarEdad.setText("");
        RegistrarDNI.setText("");
        RegistrarTipo.setText("");
        RegistrarFecha.setText("");
        RegistrarSalario.setText("");

        // Restablecer el color de los campos a gris
        RegistrarNombre.setForeground(new Color(153, 153, 153));
        RegistrarEdad.setForeground(new Color(153, 153, 153));
        RegistrarDNI.setForeground(new Color(153, 153, 153));
        RegistrarTipo.setForeground(new Color(153, 153, 153));
        RegistrarFecha.setForeground(new Color(153, 153, 153));
        RegistrarSalario.setForeground(new Color(153, 153, 153));
    }
    private boolean busquedaCamposPredert() {
    String nombrePlaceholder = "Ingresar Nombre";
    String edadPlaceholder = "Ingresar Edad";
    String dniPlaceholder = "Ingresar DNI";
    String tipoPlaceholder = "Ingresar Tipo";
    String fechaPlaceholder = "Ingresar Fecha de Nacimiento";
    String salarioPlaceholder = "Ingresar Salario";

    return RegistrarNombre.getText().equals(nombrePlaceholder)
            || RegistrarEdad.getText().equals(edadPlaceholder)
            || RegistrarDNI.getText().equals(dniPlaceholder)
            || RegistrarTipo.getText().equals(tipoPlaceholder)
            || RegistrarFecha.getText().equals(fechaPlaceholder)
            || RegistrarSalario.getText().equals(salarioPlaceholder);
}
    private void RegistrarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarNombreActionPerformed

    private void RegistrarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEdadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarEdadActionPerformed

    private void RegistrarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDNIActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarDNIActionPerformed

    private void RegistrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarTipoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarTipoActionPerformed

    private void RegistrarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarFechaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarFechaActionPerformed

    private void RegistrarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarSalarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RegistrarSalarioActionPerformed

    private void RegistrarNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarNombreMousePressed
        // TODO add your handling code here:
        if (RegistrarNombre.getText().equals("Ingresar Nombre")){
            RegistrarNombre.setText("");
            RegistrarNombre.setForeground(Color.white);   
        }else{
            restablecer();
        }
    }//GEN-LAST:event_RegistrarNombreMousePressed

    private void RegistrarEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarEdadMousePressed
        // TODO add your handling code here:
        if (RegistrarEdad.getText().equals("Ingresar Edad")){
            RegistrarEdad.setText("");
            RegistrarEdad.setForeground(Color.white);   
        }else{
            restablecer();
        }
    }//GEN-LAST:event_RegistrarEdadMousePressed

    private void RegistrarDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarDNIMousePressed
        // TODO add your handling code here:
        if (RegistrarDNI.getText().equals("Ingresar DNI")){
            RegistrarDNI.setText("");
            RegistrarDNI.setForeground(Color.white);   
        }else{
            restablecer();
        }
    }//GEN-LAST:event_RegistrarDNIMousePressed

    private void RegistrarTipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarTipoMousePressed
        // TODO add your handling code here:
        if (RegistrarTipo.getText().equals("Ingresar Tipo")){
            RegistrarTipo.setText("");
            RegistrarTipo.setForeground(Color.white);   
        }else{
            restablecer();
        }
    }//GEN-LAST:event_RegistrarTipoMousePressed

    private void RegistrarFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarFechaMousePressed
        // TODO add your handling code here:
        if (RegistrarFecha.getText().equals("Ingresar Fecha de Nacimiento")){
            RegistrarFecha.setText("");
            RegistrarFecha.setForeground(Color.white);   
        }else{
            restablecer();
        }
    }//GEN-LAST:event_RegistrarFechaMousePressed

    private void RegistrarSalarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarSalarioMousePressed
        // TODO add your handling code here:
        if (RegistrarSalario.getText().equals("Ingresar Salario")){
            RegistrarSalario.setText("");
            RegistrarSalario.setForeground(Color.white);   
        }else{
            restablecer();
        }
    }//GEN-LAST:event_RegistrarSalarioMousePressed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistrarActionPerformed
     // Lista para almacenar los datos a guardar
    
    private void BotonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseClicked
        // TODO add your handling code here:
        String nombre = RegistrarNombre.getText();
        String edad = RegistrarEdad.getText();
        String dni = RegistrarDNI.getText();
        String tipo = RegistrarTipo.getText();
        String fecha = RegistrarFecha.getText();
        String salario = RegistrarSalario.getText();
        if (!nombre.isEmpty() && !edad.isEmpty() && !dni.isEmpty() && !tipo.isEmpty() && !fecha.isEmpty() && !salario.isEmpty()) {
        // Verificar si se ha seleccionado un cargo válido
            if (!cargoSeleccionado.equals("Seleccionar cargo")&& !busquedaCamposPredert()) {
                Empleados empleado = new Empleados(nombre, edad, dni, tipo, fecha, salario, cargoSeleccionado);
                //listaDatos.add(empleado);
                Datos.agregarEmpleado(empleado); 
                mostrarDialogoConfirmacion(empleado);
                limpiarCampos();
            } else {
                // Si el campo de cargo no ha sido seleccionado, mostrar un mensaje de error
                mostrarDialogoError();
            }
        } else {
            // Si algún campo está vacío, muestra un mensaje de error
            mostrarDialogoError();
        }
    }//GEN-LAST:event_BotonRegistrarMouseClicked

    private void OpcionesCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesCargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesCargosActionPerformed

    private void OpcionesCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpcionesCargosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesCargosMouseClicked

    private void OpcionesCargosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpcionesCargosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
           cargoSeleccionado = (String) OpcionesCargos.getSelectedItem();
            switch (cargoSeleccionado) {
                case "Seleccionar cargo":
                    break;
                case "Tecnico":
                    break;
                case "Ingeniero":
                    break;
                case "Vendedor":
                    break;
                case "Servicio al Cliente":
                    break;
                default:
                    break;
            }
        }

    }//GEN-LAST:event_OpcionesCargosItemStateChanged

    private void BotonMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMenuMouseClicked
        // TODO add your handling code here
        Menu menuOpciones = new Menu();
        menuOpciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonMenuMouseClicked

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BotonMenuActionPerformed
    private void mostrarDialogoConfirmacion(Empleados empleado) {
    JOptionPane.showMessageDialog(this, "Los datos se han integrado correctamente.\n --------------------------------------------- \nUsuario registrado: " + empleado.getNombre() + "\nID: " + empleado.getID()+ "\nCargo: "+ empleado.getCargo(), "Confirmación", JOptionPane.INFORMATION_MESSAGE);
    }
    // Método para mostrar el diálogo de error
    private void mostrarDialogoError() {
    JOptionPane.showMessageDialog(this, "Debes completar todos los campos antes de registrar.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registrar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JComboBox<String> OpcionesCargos;
    private javax.swing.JTextField RegistrarDNI;
    private javax.swing.JTextField RegistrarEdad;
    private javax.swing.JTextField RegistrarFecha;
    private javax.swing.JTextField RegistrarNombre;
    private javax.swing.JPanel RegistrarPanel;
    private javax.swing.JTextField RegistrarSalario;
    private javax.swing.JTextField RegistrarTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables

    void setModalityType(Dialog.ModalityType modalityType) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
